[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
  "shift_monitors",
  "toggle_special",
]

[scratchpads.term]
lazy = true
command = "kitty --class kitty-scratchpad"

[scratchpads.warp]
lazy = true
position = "5% 5%"
command = "warp-terminal"
size = "90% 90%"

[scratchpads.volume]
animation = "fromtop"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "70% 40%"
unfocus = "hide"

[scratchpads.thunar]
lazy = true
command = "thunar"

[scratchpads.nautilus]
lazy = true
command = "nautilus"


[scratchpads.firefox]
lazy = true
command = "firefox"


[scratchpads.thorium]
lazy = true
command = "thorium-browser"
