# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# exports
plug "$HOME/.config/zsh/exports.zsh"

# history
HISTFILE=~/.zsh_history

# prompt
# plug "zap-zsh/zap-prompt"
plug "romkatv/powerlevel10k"

# plugins
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-history-substring-search"
plug "zap-zsh/sudo"
plug "MichaelAquilina/zsh-you-should-use"
# plug "$HOME/.config/zsh/plugins/z/z.plugin.zsh"
plug "agkozak/zsh-z"
plug "$HOME/.config/zsh/plugins/fzf/fzf.plugin.zsh"
plug "zap-zsh/fzf"
plug "Aloxaf/fzf-tab"
plug "Freed-Wu/fzf-tab-source"
export VI_MODE_ESC_INSERT="jk" && plug "zap-zsh/vim"
# plug "joshskidmore/zsh-fzf-history-search"
# instead of fzf-tab
plug "wintermi/zsh-golang"
# plug "chivalryq/git-alias"

# source
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/bindkey.zsh"

# Load and initialise completion system
autoload -Uz compinit
compinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export GOPATH="$HOME/go"; export GOROOT="$HOME/.go"; export PATH="$GOPATH/bin:$PATH"; # g-install: do NOT edit, see https://github.com/stefanmaric/g
alias gom="$GOPATH/bin/g"; # g-install: do NOT edit, see https://github.com/stefanmaric/g
