gui:
  nerdFontsVersion: "3"
confirmOnQuit: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  overrideGpg: true
keybinding:
  universal:
    return: "<c-c>"
    prevBlock-alt: "<c-k>"
    nextBlock-alt: "<c-j>"
