lastupdatecheck: 1699884556
recentrepos:
- /home/night/.dotfiles
- /home/night/ncuhome/work/labor/labor-be
- /home/night/ncuhome/work/welcome-guide-2022-be
- /home/night/hyprland-demo/hyprdots
- /home/night/ncuhome/study/blog
- /home/night/lazygit
- /home/night/hyprland-demo/dotfiles
- /home/night/code/go/get/22HomeWork-3
- /home/night/.local/share/nvim/lazy/SchemaStore.nvim
- /home/night/.local/share/nvim/lazy/go.nvim
- /home/night/schoolcode/DataStructure
- /home/night/.cache/yay/java21-jetbrains-imfix
- /home/night/ncuhome/passport
- /home/night/ncuhome/new/23-HOMEWORK-3
- /home/night/.local/share/nvim/lazy/markdown-preview.nvim
- /home/night/code
- /home/night/code/web_front/todolist
- /home/night/code/web_front/react-todo-mvc
- /home/night/code/web_front/react-jsx-demo
- /home/night/ncuhome/work/passport_app_appraising
- /home/night/ncuhome/work/PJWTC
- /home/night/code/go/dev_go
- /home/night/ncuhome/work/ncuos-rpc-v2
- /home/night/ncuhome/study/grpcStudy
- /home/night/ncuhome/demo/NCUOJ-Backend
startuppopupversion: 5
customcommandshistory:
- '"'
hidecommandlog: false
ignorewhitespaceindiffview: false
